USE [master]
GO
/****** Object:  Database [Reczept]    Script Date: 2019-07-25 15:37:42 ******/
CREATE DATABASE [Reczept]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Reczept', FILENAME = N'C:\TMP\Reczept.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Reczept_log', FILENAME = N'C:\TMP\Reczept_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Reczept] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Reczept].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Reczept] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Reczept] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Reczept] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Reczept] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Reczept] SET ARITHABORT OFF 
GO
ALTER DATABASE [Reczept] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Reczept] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Reczept] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Reczept] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Reczept] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Reczept] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Reczept] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Reczept] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Reczept] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Reczept] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Reczept] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Reczept] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Reczept] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Reczept] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Reczept] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Reczept] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Reczept] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Reczept] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Reczept] SET  MULTI_USER 
GO
ALTER DATABASE [Reczept] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Reczept] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Reczept] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Reczept] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Reczept] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Reczept] SET QUERY_STORE = OFF
GO
USE [Reczept]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Reczept]
GO
/****** Object:  Table [dbo].[Ingredient]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredient](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Namn] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipe]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipe](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Description] [varchar](2500) NULL,
 CONSTRAINT [PK_Recipe] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecipeContainsIngredient]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecipeContainsIngredient](
	[RecipeId] [int] NOT NULL,
	[IngredientId] [int] NOT NULL,
	[Quantity] [float] NULL,
	[MeasurementUnit] [int] NULL,
 CONSTRAINT [PK_RecipeContainsIngredient] PRIMARY KEY CLUSTERED 
(
	[RecipeId] ASC,
	[IngredientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SlackUser]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SlackUser](
	[MemberId] [varchar](50) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_SlackUser] PRIMARY KEY CLUSTERED 
(
	[MemberId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tag]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
 CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TagsOnRecipe]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TagsOnRecipe](
	[RecipeId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_TagsOnRecipe] PRIMARY KEY CLUSTERED 
(
	[RecipeId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Unit]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Unit](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Unit] [varchar](25) NOT NULL,
 CONSTRAINT [PK_Unit] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserHistory]    Script Date: 2019-07-25 15:37:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserHistory](
	[UserId] [varchar](50) NOT NULL,
	[RecipeId] [int] NOT NULL,
	[DateCooked] [datetime] NOT NULL,
	[UserLikesRecipe] [bit] NULL,
 CONSTRAINT [PK_UserLikesRecipe] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RecipeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RecipeContainsIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeContainsIngredient_Ingredient] FOREIGN KEY([IngredientId])
REFERENCES [dbo].[Ingredient] ([Id])
GO
ALTER TABLE [dbo].[RecipeContainsIngredient] CHECK CONSTRAINT [FK_RecipeContainsIngredient_Ingredient]
GO
ALTER TABLE [dbo].[RecipeContainsIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeContainsIngredient_Recipe] FOREIGN KEY([RecipeId])
REFERENCES [dbo].[Recipe] ([Id])
GO
ALTER TABLE [dbo].[RecipeContainsIngredient] CHECK CONSTRAINT [FK_RecipeContainsIngredient_Recipe]
GO
ALTER TABLE [dbo].[RecipeContainsIngredient]  WITH CHECK ADD  CONSTRAINT [FK_RecipeContainsIngredient_Unit] FOREIGN KEY([MeasurementUnit])
REFERENCES [dbo].[Unit] ([Id])
GO
ALTER TABLE [dbo].[RecipeContainsIngredient] CHECK CONSTRAINT [FK_RecipeContainsIngredient_Unit]
GO
ALTER TABLE [dbo].[TagsOnRecipe]  WITH CHECK ADD  CONSTRAINT [FK_TagsOnRecipe_Recipe] FOREIGN KEY([RecipeId])
REFERENCES [dbo].[Recipe] ([Id])
GO
ALTER TABLE [dbo].[TagsOnRecipe] CHECK CONSTRAINT [FK_TagsOnRecipe_Recipe]
GO
ALTER TABLE [dbo].[TagsOnRecipe]  WITH CHECK ADD  CONSTRAINT [FK_TagsOnRecipe_Tag] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
GO
ALTER TABLE [dbo].[TagsOnRecipe] CHECK CONSTRAINT [FK_TagsOnRecipe_Tag]
GO
ALTER TABLE [dbo].[UserHistory]  WITH CHECK ADD  CONSTRAINT [FK_UserLikesRecipe_Recipe] FOREIGN KEY([RecipeId])
REFERENCES [dbo].[Recipe] ([Id])
GO
ALTER TABLE [dbo].[UserHistory] CHECK CONSTRAINT [FK_UserLikesRecipe_Recipe]
GO
ALTER TABLE [dbo].[UserHistory]  WITH CHECK ADD  CONSTRAINT [FK_UserLikesRecipe_SlackUser] FOREIGN KEY([UserId])
REFERENCES [dbo].[SlackUser] ([MemberId])
GO
ALTER TABLE [dbo].[UserHistory] CHECK CONSTRAINT [FK_UserLikesRecipe_SlackUser]
GO
USE [master]
GO
ALTER DATABASE [Reczept] SET  READ_WRITE 
GO
